mongo:
  image: yongjhih/mongo-rocks
  ports:
    - "27017:27017"
  volumes_from:
    - mongo-data
  #environment:
    #- MONGO_ROOT_PASSWORD=root
    #- MONGO_USER=user
    #- MONGO_PASSWORD=user
    #- MONGO_DATABASE=dev
  command: "--smallfiles --logpath=/dev/null --setParameter failIndexKeyTooLong=false --storageEngine rocksdb"

mongo-data:
  image: yongjhih/mongo-rocks
  volumes:
    - /data/db
  command: "--break-mongo"
