version: '2'

volumes:
  mongo-data:

mongo:
  image: yongjhih/mongo-rocks:parse
  ports:
    - "27017:27017"
  volumes:
    - mongo-data:/data/db
  #environment:
    #- MONGO_ROOT_PASSWORD=root
    #- MONGO_USER=user
    #- MONGO_PASSWORD=password
    #- MONGO_DATABASE=dev
  command: "--smallfiles --setParameter failIndexKeyTooLong=false --setParameter internalQueryExecYieldPeriodMS=1000 --setParameter internalQueryExecYieldIterations=100000"
